version: "3"
services:
    nginx:
      image: nginx:latest
      container_name: nginx1
      ports:
        - 80:80
      restart: always
      volumes:
        - ./main_app/static:/static
        - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - web

    web:
      build: ./
      container_name: app
      expose:
        - 8080
      ports:
        - 8080:8080

    mongodb:
      image: mongo:latest
      container_name: "mongodb"
      ports:
          - 27017:27017
